apiVersion: apps/v1
kind: Deployment
metadata:
  name: store_service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store_service 
  template:
    metadata:
      labels:
        app: store_service
    spec:
      containers:
        - name: store_service
          image: elmostaine/store_service_dev
          env:
            - name: NODE_ENV
              value: 'PROD'
      imagePullSecrets:
        - name: regcred
        
---
apiVersion: v1
kind: Service
metadata:
  name: store_service-srv
spec:
  selector:
    app: store_service
  ports:
    - name: store_service
      protocol: TCP
      port: 5000
      targetPort: 5000
